apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reporter.labels" . | nindent 4 }}
data:
  config.yml: |
    reporters:
      {{- toYaml .Values.reporters | nindent 6 }}
    hpa:
      {{- toYaml .Values.hpaList | nindent 6 }}